# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Longriver
tagline:          Life is a long quite river.
url:              http://blog.longriver.com
paginate:         5
baseurl:          /
author:
  name:           Harvey
  url:            https://twitter.com/harveyaot
  email:          informan@163.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/harveyaot/haryaot.github.io

pages_list: 
    Archive: '/archive'
    ML: '/ml_cat'
    Coding: '/coding_cat'
    Feed: '/atom.xml'
images_base_dir: '/public/images'
